version: '3.9'

services:
  # Gateway service
  gateway-service:
    build: ./api-gateway
    container_name: gateway-service
    ports:
      - "8080:8080"
    networks:
      - moustass-network

  # Auth DB
  auth-db:
    image: mysql:8
    container_name: auth-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_db
    volumes:
      - auth_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - moustass-network

  # Notification DB
  notification-db:
    image: mysql:8
    container_name: notification-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notifications_db
    volumes:
      - notification_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - moustass-network

  # Auth Service
  auth-service:
    build: ./services/auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://auth-db:3306/user_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      auth-db:
        condition: service_healthy
    networks:
      - moustass-network

# Key Service
  # KMS DB
  kms-db:
    image: mysql:8
    container_name: kms-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kms_db
    ports:
      - "3310:3306"
    volumes:
      - kms_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - moustass-network

  # KMS Service
  kms-service:
    build: ./services/kms-service
    container_name: kms-service
    ports:
      - "8083:8083"
    volumes:
      - ./services/kms-service/.env:/app/.env:ro
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://kms-db:3306/kms_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      kms-db:
        condition: service_healthy
    networks:
      - moustass-network

# Transaction Service
  transactions-db:
    image: mysql:8
    container_name: transactions-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: transactions_db
    ports:
      - "3311:3306"
    volumes:
      - transactions_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - moustass-network

  transactions-service:
    build: ./services/transactions-service
    container_name: transactions-service
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://transactions-db:3306/transactions_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      transactions-db:
        condition: service_healthy
    networks:
      - moustass-network
      
  # Notification Service
  notification-service:
    build: ./services/notification-service
    container_name: notification-service
    ports:
      - "8092:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://notification-db:3306/notifications_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      notification-db:
        condition: service_healthy
    networks:
      - moustass-network

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
    - moustass-network
    
  # FRONTEND (Next.js)
  # Frontend (Next.js)
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://gateway-service:8080
    depends_on:
      - gateway-service
    networks:
      - moustass-network

networks:
  moustass-network:
    driver: bridge

volumes:
  auth_data:
  kms_data:
  transactions_data:
  minio_data:
  notification_data:
